-- SupabaseのSQLエディタで以下のクエリを実行して、reservationsテーブルを作成してください。

create table reservations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  pickup_time timestamp with time zone not null,
  items jsonb not null,
  total_price integer not null
);

-- RLS（Row Level Security）ポリシーの設定（オプションですが推奨）
-- 誰でも追加（予約）できるが、閲覧は管理者のみにする場合の設定例

alter table reservations enable row level security;

-- 予約の作成は誰でも許可
create policy "Enable insert for everyone" on reservations for insert with check (true);

-- 予約の参照は管理者のみ（supabaseのauth.uid()などを使う場合）
-- 簡易的に現在は全員読み取り可能にするなら以下（本番運用では注意）
create policy "Enable read for everyone" on reservations for select using (true);

-- または、管理者ユーザーのみが見れるように認証ロジックと組み合わせる必要がありますが、
-- 今回のクライアントサイドコードは単純にselectしているので、とりあえずReadも許可しておく必要があります。
-- （main.jsのfetchReservationsは認証済みかチェックしていますが、Supabase側での制限も重要です）
